### ISSUE TITLE
譜面終了時に譜面と動画が止まってしまう

### ISSUE THREAD

**Issue by nyoro-wrl** [Koioto/Koioto-Issues#18]
### 譜面が止まる
譜面終了と同時に譜面の動きが止まります。

明確なバグとしては、判定も止まったままなので、最後に音符が配置されていると曲が終わった後に叩いてもPERFECT判定が出る他、連打の終端で終わると永久に連打数を増やせてしまいます。

個人的には他のシミュレーターと同等に、譜面が終わった後も左に流れていくようにしてほしいです。最後の音符を叩き損ねると音符が画面上に残り続けるのはどうにも格好悪いです。

### 動画が止まる
譜面終了と同時に背景の動画が止まります。

**Comment by AioiLight** [comment]
譜面が止まる、というのは何もない、空の1小節を作るということで対応します。

動画については、単純に動画が止まらないようにいたします。

**Comment by AioiLight** [comment]
両方ともVer.0.3で修正されます。
