### ISSUE TITLE
一部音源で勝手にループしてしまう

### ISSUE THREAD

**Issue by AioiLight** [Koioto/Koioto-Issues#20]
特定のフォーマット、形式で音源が勝手にループしてしまう現象がある。

多分DXライブラリ側の不具合。
どのように再現するかは不明。要追加情報

**Comment by nyoro-wrl** [comment]
あらゆるフォーマットの音源で検証してみました。
結論から言うと、検証の範囲内でループが起こる音源はありませんでした。

## 問題なし
- wav
  - 8Hz 16bit
  - 44kHz 16bit
  - 44kHz 24bit
  - 44kHz 32bit(Float)
  - 48kHz 16bit
  - 96kHz 16bit
  - 384kHz 32bit(Float)
- mp3
  - CBR 44kHz
  - ABR 44kHz
  - VBR 44kHz
- ogg
  - 44kHz
  - 48kHz
- flac
  - 44kHz 16bit
  - 48kHz 16bit
- aac
  - 44kHz 16bit（拡張子.m4a）
  - 44kHz 16bit（拡張子.aac）
- alac
  - 44kHz 16bit
  - 96kHz 16bit
  - 192kHz 16bit
- wma 44kHz 16bit
- wavpack 44kHz 16bit
- dts 48kHz 16bit

## 無音
- flac
  - 44kHz 24bit
  - 88kHz 16bit
  - 96kHz 16bit

## 数秒経つと無音
- ape 44kHz 16bit

## ノイズ発生
- wav
  - 44kHz 24bit(i32)
  - 44kHz 32bit
- alac
  - 44kHz 32bit
  - 96kHz 32bit
  - 192kHz 32bit

## 強制終了
- alac
  - 44kHz 24bit
  - 96kHz 24bit
  - 192kHz 24bit

**Comment by AioiLight** [comment]
現時点ではDXライブラリで扱えるフォーマットしか再生できないので、FLACなどのフォーマットは再生できません

この不具合は、今回テーマ曲の音源を新しいものに差し替えたときに発生しました
もとのMediainfo
```
フォーマット                                   : Wave
サイズ                                      : 22.7 MiB
ながさ                                      : 2分 14秒
OBR モード                                  : CBR モード
オーバルビットレート                               : 1 411 Kbps
使用したエンコーダ                                : FL Studio 20

オーディオ
フォーマット                                   : PCM
設定                                       : Little / Signed
コーデック ID                                 : 1
ながさ                                      : 2分 14秒
ビットレートモード                                : CBR モード
ビットレート                                   : 1 411.2 Kbps
チャンネル                                    : 2 チャンネル
サンプルレート                                  : 44.1 KHz
BitDepth/String                          : 16 ビット
ストリームサイズ                                 : 22.7 MiB (100%)
```

そして、ごく単純に、Adobe Auditionで保存をし直したところ、問題なく再生するようになりました

```
フォーマット                                   : Wave
サイズ                                      : 22.7 MiB
ながさ                                      : 2分 14秒
OBR モード                                  : CBR モード
オーバルビットレート                               : 1 411 Kbps

オーディオ
フォーマット                                   : PCM
設定                                       : Little / Signed
コーデック ID                                 : 1
ながさ                                      : 2分 14秒
ビットレートモード                                : CBR モード
ビットレート                                   : 1 411.2 Kbps
チャンネル                                    : 2 チャンネル
サンプルレート                                  : 44.1 KHz
BitDepth/String                          : 16 ビット
ストリームサイズ                                 : 22.7 MiB (100%)
```

おま環である可能性も高いので、しばらくは様子見で。。。

**Comment by Project6400** [comment]
FLAC再生出来ました（44KHz 16Bit）

これは明らかにおま環な気が()

**Comment by AioiLight** [comment]
【解決】FL Studioでは、ファイルの書き出しを行うと自動的にループするようなメタデータを埋め込むそうです。別の音楽編集ソフトでメタデータを除去すれば、問題無く再生できます。

DXライブラリでは、ループのメタデータが含まれている場合、1度のみ再生するよう指定しても、メタデータに従いループ再生を行うようであり、仕様だそうです。
