### ISSUE TITLE
テーマ側でプラグインを呼べるようにする

### ISSUE THREAD

**Issue by nyoro-wrl** [Koioto/Koioto-Issues#32]
将来的に必要になってくる機能かと思われます。
テーマごとの独自機能や、ビジュアルを実装する際に使います。

具体的にはテーマ内にPluginファイルを用意するなど。

**Comment by AioiLight** [comment]
現時点でプラグインフォルダにDLLを設置し、DrawOrderにプラグインのフルネームを書けば同様のことが出来ますがどうでしょうか
（テーマ本体から呼び出すようにすれば必然的にDrawOrderと干渉してしまうのでそこを解決する必要があります）

**Comment by nyoro-wrl** [comment]
テーマの導入/削除時に、ThemeフォルダとPluginフォルダの2つを使うことになるのがあまり好ましくないです。
テーマをThemeフォルダに入れる/削除するだけで導入/削除ができるようにしたほうがユーザビリティが高いかと思われます。

**Comment by AioiLight** [comment]
テーマとプラグインは全くの別物だと考えてください。あくまでも テーマというのは Koioto 標準で備わっている機能や演出の見た目を変更する為のもので、プラグインの見た目を変更するものではありません

また「テーマにプラグインを同梱させる」という行為は非推奨です。テーマとプラグインに親子関係は無く、それぞれは独立しています
(プラグインが何か描画作業を行う必要がある場合のみに限り、描画順番を変更できるという使用上テーマと干渉します)

**Comment by AioiLight** [comment]
Koioto の性質上、確かにそのような仕様にした方が便利が良いのは理解できますが、プラグイン自体、オプショナルなものであるので テーマ自体にプラグインを埋め込むという考えは **いまのところ** ありません。

Koioto 自体の基本機能として 極めて一般的な使い方をするユーザーが満足するレベルの機能は全て実装すると考えていただければ。
