### ISSUE TITLE
連打の見た目が判定より短く描画されてしまっている

### ISSUE THREAD

**Issue by nyoro-wrl** [Koioto/Koioto-Issues#33]

**Comment by Project6400** [comment]
これにより
[ "5000000000000008" ]
で譜面が終わる時連打が無限に入れられる(報告済み？)

**Comment by AioiLight** [comment]
> これにより
> [ "5000000000000008" ]
> で譜面が終わる時連打が無限に入れられる(報告済み？)

直接Issueのタイトルの現象と関係がないはずですので、Ver.0.3でも再現できたら独立したIssueを立ててもらえると幸いです。

**Comment by AioiLight** [comment]
Ver.0.7で修正されます。
![image](https://user-images.githubusercontent.com/13918537/90390769-e5192c00-e0c6-11ea-90f1-e79c7217e123.png)
