### ISSUE TITLE
開始BPMが極端に低い/高い場合、最初の音符を叩くのに時間がかかってしまったり、逆に一瞬だったりしてしまう

### ISSUE THREAD

**Issue by nyoro-wrl** [Koioto/Koioto-Issues#34]
譜面開始時に、小節の挿入のみで対応しているのがおそらくの原因（かかる時間がBPMに依存してしまう）。
終了時もおそらく同様の処理なので、今後実装されるであろうリザルト画面への以降時間に大きなバラつきが発生することが予想されます。

またレアケースだとは思いますが、自分の譜面に開始BPMが0の譜面があります。
これは一生流れてこないどころか、強制終了してしまいます（他のシミュレーターでは正常に再生できます）。

**Comment by AioiLight** [comment]
音楽にテンポがない(BPM:0)というのはあり得ないので、BPMが0の場合、他のシミュレータではどのような挙動をするか教えていただければ。単純に既定値を指定するだけでしょうか？

**Comment by nyoro-wrl** [comment]
前提としてBPM:0に設定し、最初の小節の頭に#BPMCHANGEを使った譜面になっています（あと#BMSCROLL）。
挙動としては演奏画面に移行した瞬間から譜面が停止しており、OFFSET:の時間後に最初の小節が開始されます。小節の頭に#BPMCHANGEが設定されているため、譜面が動きだすといった感じです。

**Comment by nyoro-wrl** [comment]
ビジュアル的には、譜面の開始前から#DELAYが働いている…といった感覚に近いです。

**Comment by AioiLight** [comment]
ナルホド……わかりました、対応するかどうかは検討させてください。

**Comment by AioiLight** [comment]
Ver.0.20のOpenTaikoChartプラグインにて、一律3秒の前後オフセットを行うように変更しました。
