### ISSUE TITLE
背景動画の色が変色する

### ISSUE THREAD

**Issue by AioiLight** [Koioto/Koioto-Issues#41]
ごくまれに背景動画が変色する。

動画再生が始まると、問題無く再生される

どのコーデックでも発生すると思われる。多分DXLibの不具合。

**Comment by AioiLight** [comment]
![image](https://user-images.githubusercontent.com/13918537/89722932-8bf82b00-da2a-11ea-8af8-552fb4609cd9.png)

これだ

**Comment by AioiLight** [comment]
![image](https://user-images.githubusercontent.com/13918537/89722937-b9dd6f80-da2a-11ea-9fe2-25ea88d5780f.png)
正常な場合

**Comment by AioiLight** [comment]
変色のパターンとして、グリーンバック、一部の色が落ちる(退色？)、ほとんどのピクセルが真っ黒になる などがある。

**Comment by Project6400** [comment]
![タイトルなし](https://user-images.githubusercontent.com/65718610/89734349-8afce300-da96-11ea-9d98-59eb8bd15338.png)
画像読み込み

**Comment by AioiLight** [comment]
無理矢理マルチスレッド処理を行っていたのが原因でこのような不具合を起こしていた可能性があります。DXLibがマルチスレッドに向いていないため、しばらく同期処理に変更します。
